### ISSUE TITLE
np.linalg.solve fails on some datasets

### ISSUE THREAD

**Issue by louis-kilfoyle** [RianneSchouten/pymice#1]
Running mcar_test() on some datasets fails because the covariance matrix is degenerate.
https://github.com/RianneSchouten/pymice/blob/master/pymice/exploration/mcar_tests.py#L86

My datasets have dummy variables used to encode categorical values, so I tried dropping one dummy in hopes of removing the collinearity, but without success.

I tried replacing np.linalg.solve with np.linalg.lstsq to produce an approximate solution, but the results are questionable. The test returns p-values of exactly 1.0 or 0.0 for many of my datasets.

**Comment by RianneSchouten** [comment]
At the moment, the mcar_test() does not work for variables other than continuous. I recommend to check the r function that does the same kind of test. You find the documentation here: https://www.rdocumentation.org/packages/BaylorEdPsych/versions/0.5/topics/LittleMCAR

Be aware that little's mcar test tests whether there are no systematic differences between missing values and observed values for the other variables. This means, that 9 of your 10 variables could be MCAR, and 1 MAR, and the test will give the answer 'No'. Be aware too, that if the answer is 'Yes', the real underlying mechanism could still be MNAR (the reason for the missingness is then outside your dataset). The MCAR test might help to understand the data, but it is never a one and only answer. 

Hope this helps.
