### ISSUE TITLE
Column name shift lookup table does not match

### ISSUE THREAD

**Issue by RianneSchouten** [RianneSchouten/pymice#16]
When I run with prop = 0.1 and sigmoid-right, the right value in the lookup table cannot be found.
If I check the lookup table, that particular column is 0.09999999.
Is it an idea to round all column values to two decimals in the lookup table?

**Comment by davzaman** [comment]
this should be fixed in 3252765, please close the issue if it has! Better yet, we should probably write a test.

**Comment by RianneSchouten** [comment]
Super!
